import{test}from'node:test';import assert from'node:assert/strict';import{createWorldState}from'../sim/world';import{createClusterState}from'../sim/clusters/state';import{applyNeedleUrchinAI,fireNeedleBurst,segmentAabbHitT,shouldTriggerNeedleUrchin,tickNeedleUrchinProjectiles}from'../sim/clusters/needleUrchinAi';import*as C from'../sim/clusters/needleUrchinConfig';import{enemyFlagsToType}from'../levels/roomSchemaV2';import{enemyTypeToFlags}from'../levels/roomSchemaHydrator';import type{RoomJsonEnemy}from'../editor/roomJsonSchema';
function fx(){const w=createWorldState(1000/60,2),p=createClusterState(0,50,20,1,10),u=createClusterState(1,20,20,0,3);u.isNeedleUrchinFlag=1;u.needleUrchinSlotIndex=0;u.halfWidthWorld=u.halfHeightWorld=6;w.worldWidthWorld=w.worldHeightWorld=200;w.clusters=[p,u];return{w,p,u};}
test('trigger uses total speed strictly above 80',()=>{assert.equal(shouldTriggerNeedleUrchin(10,0,80,0),false);assert.equal(shouldTriggerNeedleUrchin(10,0,0,81),true);assert.equal(shouldTriggerNeedleUrchin(97,0,100,0),false);});
test('telegraph cancels when player slows',()=>{const{w,p,u}=fx();p.velocityXWorld=81;applyNeedleUrchinAI(w);assert.equal(u.needleUrchinState,C.NEEDLE_URCHIN_STATE_TELEGRAPH);p.velocityXWorld=80;applyNeedleUrchinAI(w);assert.equal(u.needleUrchinState,C.NEEDLE_URCHIN_STATE_IDLE);assert.equal(w.needleProjectileAliveFlag.reduce((a,b)=>a+b,0),0);});
test('completed telegraph fires exactly twelve evenly spaced needles',()=>{const{w,p,u}=fx();p.velocityXWorld=81;for(let i=0;i<=C.NEEDLE_URCHIN_TELEGRAPH_TICKS;i++)applyNeedleUrchinAI(w);assert.equal(w.needleProjectileAliveFlag.reduce((a,b)=>a+b,0),12);const angles=[];for(let i=0;i<12;i++)angles.push(Math.atan2(w.needleProjectileVelYWorld[i],w.needleProjectileVelXWorld[i]));assert.ok(Math.abs(w.needleProjectileVelYWorld[0])<1e-4);assert.equal(u.needleUrchinState,C.NEEDLE_URCHIN_STATE_COOLDOWN);});
test('burst overwrite remains within owner range',()=>{const{w,u}=fx();fireNeedleBurst(w,u);assert.equal(w.needleProjectileAliveFlag.length,C.MAX_NEEDLE_URCHINS*12);assert.equal(w.needleProjectileAliveFlag.slice(12).reduce((a,b)=>a+b,0),0);});
test('segment AABB is swept and returns earliest hit',()=>{assert.equal(segmentAabbHitT(0,0,10,0,4,-1,6,1),.4);assert.equal(segmentAabbHitT(0,0,10,0,12,-1,14,1),null);});
test('wall collision wins before player and despawns needle',()=>{const{w,p}=fx();p.positionXWorld=80;w.wallCount=1;w.wallXWorld[0]=40;w.wallYWorld[0]=0;w.wallWWorld[0]=8;w.wallHWorld[0]=40;w.needleProjectileAliveFlag[0]=1;w.needleProjectileXWorld[0]=20;w.needleProjectileYWorld[0]=20;w.needleProjectileVelXWorld[0]=4000;w.needleProjectileLifetimeTicks[0]=10;tickNeedleUrchinProjectiles(w);assert.equal(w.needleProjectileAliveFlag[0],0);assert.equal(p.healthPoints,10);});
test('needle bypasses momentum guard but respects ordinary invulnerability',()=>{const{w,p}=fx();p.positionXWorld=22;p.isHighVelocityAttacking=1;w.needleProjectileAliveFlag[0]=1;w.needleProjectileXWorld[0]=20;w.needleProjectileYWorld[0]=20;w.needleProjectileVelXWorld[0]=180;w.needleProjectileLifetimeTicks[0]=10;tickNeedleUrchinProjectiles(w);assert.equal(p.healthPoints,9);p.invulnerabilityTicks=10;w.needleProjectileAliveFlag[0]=1;tickNeedleUrchinProjectiles(w);assert.equal(p.healthPoints,9);});
test('compact schema preserves urchin identity',()=>{const t=enemyFlagsToType({isNeedleUrchin:true}as RoomJsonEnemy);assert.equal(t,'needleUrchin');assert.equal(enemyTypeToFlags(t,{xBlock:1,yBlock:1,kinds:['Physical'],particleCount:3,isBoss:false}).isNeedleUrchin,true);});
