import{test}from'node:test';import assert from'node:assert/strict';import{createWorldState}from'../sim/world';import{createClusterState}from'../sim/clusters/state';import{appendShadowWaypoint,clearShadowPath,recordAndMoveShadowEnemies,resolveShadowFatalContacts}from'../sim/clusters/shadowEnemyAi';import{SHADOW_PATH_CAPACITY,SHADOW_START_DELAY_TICKS}from'../sim/clusters/shadowEnemyConfig';import{updateMomentumCombatState,applyMomentumCombatCollisionDamage}from'../sim/momentumCombat';import{enemyFlagsToType}from'../levels/roomSchemaV2';import{enemyTypeToFlags}from'../levels/roomSchemaHydrator';import type{RoomJsonEnemy}from'../editor/roomJsonSchema';
function fx(){const w=createWorldState(1000/60,1);w.combatMode='momentum';const p=createClusterState(0,40,20,1,10),s=createClusterState(1,0,20,0,1);s.isShadowEnemyFlag=1;s.shadowPathSlotIndex=0;s.shadowStartupTicks=0;s.halfWidthWorld=3.5;s.halfHeightWorld=10;w.clusters=[p,s];w.shadowPathLastRecordedXWorld[0]=p.positionXWorld;w.shadowPathLastRecordedYWorld[0]=p.positionYWorld;return{w,p,s};}
test('bounded queue discards oldest unread waypoint',()=>{const{w}=fx();for(let i=0;i<SHADOW_PATH_CAPACITY+2;i++)appendShadowWaypoint(w,0,i,0);assert.equal(w.shadowPathCount[0],SHADOW_PATH_CAPACITY);assert.equal(w.shadowPathHead[0],2);});
test('startup records path but does not move or kill',()=>{const{w,p,s}=fx();s.shadowStartupTicks=SHADOW_START_DELAY_TICKS;const x=s.positionXWorld;recordAndMoveShadowEnemies(w);resolveShadowFatalContacts(w);assert.equal(s.positionXWorld,x);assert.equal(p.isAliveFlag,1);assert.ok(w.shadowPathCount[0]>0);});
test('shadow follows recorded waypoints rather than current direct target',()=>{const{w,p,s}=fx();clearShadowPath(w,0);appendShadowWaypoint(w,0,0,40);p.positionXWorld=100;p.positionYWorld=20;w.shadowPathLastRecordedXWorld[0]=100;w.shadowPathLastRecordedYWorld[0]=20;recordAndMoveShadowEnemies(w);assert.ok(s.positionYWorld>20);});
test('teleport clears queue and starts rephase',()=>{const{w,p,s}=fx();appendShadowWaypoint(w,0,2,2);p.positionXWorld=200;recordAndMoveShadowEnemies(w);assert.ok(s.shadowRephaseTicks>0);assert.equal(w.shadowPathCount[0],1);});
test('surviving contact kills immediately despite invulnerability',()=>{const{w,p,s}=fx();s.positionXWorld=p.positionXWorld;s.positionYWorld=p.positionYWorld;p.invulnerabilityTicks=99;p.isHighVelocityAttacking=1;resolveShadowFatalContacts(w);assert.equal(p.isAliveFlag,0);assert.equal(p.healthPoints,0);});
test('momentum collision kills one-HP shadow before fatal contact',()=>{const{w,p,s}=fx();s.positionXWorld=p.positionXWorld;s.positionYWorld=p.positionYWorld;p.velocityXWorld=400;updateMomentumCombatState(w);applyMomentumCombatCollisionDamage(w);resolveShadowFatalContacts(w);assert.equal(s.isAliveFlag,0);assert.equal(p.isAliveFlag,1);});
test('compact schema preserves shadow identity',()=>{const t=enemyFlagsToType({isShadowEnemy:true}as RoomJsonEnemy);assert.equal(t,'shadow');assert.equal(enemyTypeToFlags(t,{xBlock:1,yBlock:1,kinds:['Void'],particleCount:1,isBoss:false}).isShadowEnemy,true);});
