/**
 * Centralized loading and animation controller for Dust Container and Shard Container sprites.
 * Provides randomly crossfaded frame transitions for active (filled) dust containers both
 * on the game HUD and inside inventory loadout DOM elements.
 *
 * The game HUD draws containers into a small (~10x11px) virtual-pixel slot. Downsampling the
 * native 30x33px art to that size at runtime with nearest-neighbor sampling can land exactly on
 * the sprite's dark outline column on every draw, producing a solid vertical line artifact.
 * To avoid that, the HUD path uses pre-baked, alpha-weighted-downsampled frames generated by
 * `scripts/generate-dust-container-hud-frames.mjs` (run via `npm run generate:dustContainerHudFrames`)
 * instead of scaling the native art directly. The loadout menus, which render at/near native
 * resolution, continue to use the native-resolution art.
 */

import { loadImg, isSpriteReady, decodeImg } from '../imageCache';

const ANIM_FRAME_COUNT = 10;

// ── Native-resolution assets (used by loadout/inventory menus) ─────────────

let _emptyImg: HTMLImageElement | undefined;
let _fullFallbackImg: HTMLImageElement | undefined;
let _animFrames: HTMLImageElement[] | undefined;
let _shardImgs: HTMLImageElement[] | undefined;

export function getDustContainerEmptyImg(): HTMLImageElement {
  if (_emptyImg === undefined) {
    _emptyImg = loadImg('SPRITES/DUST/DustContainer/DustContainerFrame_Empty.png');
  }
  return _emptyImg;
}

export function getDustContainerFullImg(): HTMLImageElement {
  if (_fullFallbackImg === undefined) {
    _fullFallbackImg = loadImg('SPRITES/DUST/DustContainer/DustContainerFrame_Full.png');
  }
  return _fullFallbackImg;
}

export function getDustContainerAnimFrame(frameIndex: number): HTMLImageElement {
  if (_animFrames === undefined) {
    _animFrames = [];
    for (let i = 1; i <= ANIM_FRAME_COUNT; i++) {
      _animFrames.push(loadImg(`SPRITES/DUST/DustContainer/Animation/DustContainerAnimation_Frame (${i}).png`));
    }
  }
  const safeIdx = ((Math.floor(frameIndex) % ANIM_FRAME_COUNT) + ANIM_FRAME_COUNT) % ANIM_FRAME_COUNT;
  return _animFrames[safeIdx];
}

export function getShardContainerImg(shardCount: number): HTMLImageElement {
  if (_shardImgs === undefined) {
    _shardImgs = [
      loadImg('SPRITES/DUST/ShardContainer/ShardContainer_Empty.png'),
      loadImg('SPRITES/DUST/ShardContainer/ShardContainer_OneShard.png'),
      loadImg('SPRITES/DUST/ShardContainer/ShardContainer_TwoShards.png'),
      loadImg('SPRITES/DUST/ShardContainer/ShardContainer_ThreeShards.png'),
    ];
  }
  const safeCount = Math.max(0, Math.min(3, Math.floor(shardCount)));
  return _shardImgs[safeCount];
}

// ── HUD-resolution assets (pre-downsampled; used by the in-game HUD) ───────

let _hudEmptyImg: HTMLImageElement | undefined;
let _hudFullFallbackImg: HTMLImageElement | undefined;
let _hudAnimFrames: HTMLImageElement[] | undefined;

export function getDustContainerHudEmptyImg(): HTMLImageElement {
  if (_hudEmptyImg === undefined) {
    _hudEmptyImg = loadImg('SPRITES/DUST/DustContainer/DustContainerFrame_Empty_Hud.png');
  }
  return _hudEmptyImg;
}

export function getDustContainerHudFullImg(): HTMLImageElement {
  if (_hudFullFallbackImg === undefined) {
    _hudFullFallbackImg = loadImg('SPRITES/DUST/DustContainer/DustContainerFrame_Full_Hud.png');
  }
  return _hudFullFallbackImg;
}

export function getDustContainerHudAnimFrame(frameIndex: number): HTMLImageElement {
  if (_hudAnimFrames === undefined) {
    _hudAnimFrames = [];
    for (let i = 1; i <= ANIM_FRAME_COUNT; i++) {
      _hudAnimFrames.push(loadImg(`SPRITES/DUST/DustContainer/AnimationHud/DustContainerAnimation_Frame (${i}).png`));
    }
  }
  const safeIdx = ((Math.floor(frameIndex) % ANIM_FRAME_COUNT) + ANIM_FRAME_COUNT) % ANIM_FRAME_COUNT;
  return _hudAnimFrames[safeIdx];
}

let _hudFramesPreloadStarted = false;

/**
 * Kicks off decoding of every HUD-resolution dust container frame up front, so the in-game
 * HUD never has to fall back to a placeholder rectangle mid-animation due to a frame that
 * hasn't finished loading/decoding yet. Safe to call multiple times.
 */
export function preloadDustContainerHudFrames(): void {
  if (_hudFramesPreloadStarted) return;
  _hudFramesPreloadStarted = true;
  void decodeImg('SPRITES/DUST/DustContainer/DustContainerFrame_Empty_Hud.png');
  void decodeImg('SPRITES/DUST/DustContainer/DustContainerFrame_Full_Hud.png');
  for (let i = 1; i <= ANIM_FRAME_COUNT; i++) {
    void decodeImg(`SPRITES/DUST/DustContainer/AnimationHud/DustContainerAnimation_Frame (${i}).png`);
  }
}

// ── Per-slot crossfade animation state ──────────────────────────────────────

interface SlotAnimState {
  currentFrame: number;
  targetFrame: number;
  /** Timestamp (ms) the current crossfade began; also the reference for hold timing. */
  startMs: number;
  /** How long the crossfade itself takes, in ms. */
  durationMs: number;
  /** How long to hold on the target frame (fully settled) before starting the next crossfade. */
  holdMs: number;
  /** True while the crossfade is animating; false while holding on the settled target frame. */
  crossfading: boolean;
  _warnedMissingFrame: boolean;
}

const _slotStates = new Map<number, SlotAnimState>();

interface SlotFillState {
  isFilled: boolean;
  transitionStartMs: number;
}

const _slotFillStates = new Map<number, SlotFillState>();
export const HUD_FILL_CROSSFADE_MS = 120;
export const HUD_AMBIENT_CROSSFADE_SPEED_MULTIPLIER = 5;

function randomFrameExcluding(exclude: number): number {
  let next = Math.floor(Math.random() * ANIM_FRAME_COUNT);
  if (next === exclude) next = (next + 1) % ANIM_FRAME_COUNT;
  return next;
}

/** Creates fresh, independently-randomized animation state for a slot. */
function createSlotState(nowMs: number, speedMultiplier = 1): SlotAnimState {
  // Randomized initial frame and an initial phase offset (a randomized starting point
  // within the first cycle) so freshly-created slots don't all animate in lockstep.
  const initialFrame = Math.floor(Math.random() * ANIM_FRAME_COUNT);
  const targetFrame = randomFrameExcluding(initialFrame);
  const durationMs = (400 + Math.floor(Math.random() * 400)) / speedMultiplier;
  const phaseOffsetMs = Math.floor(Math.random() * durationMs);
  return {
    currentFrame: initialFrame,
    targetFrame,
    startMs: nowMs - phaseOffsetMs,
    durationMs,
    holdMs: Math.floor(Math.random() * 600),
    crossfading: true,
    _warnedMissingFrame: false,
  };
}

/** Advances slot state past any elapsed crossfades/holds, looping as many times as needed. */
function advanceSlotState(state: SlotAnimState, nowMs: number, speedMultiplier = 1): void {
  // Bounded loop: with realistic durations/hold times and frame deltas this resolves in a
  // handful of iterations even after a long tab-backgrounding gap; the cap just prevents any
  // pathological input from hanging the render loop.
  for (let guard = 0; guard < 64; guard++) {
    const phaseMs = state.crossfading ? state.durationMs : state.holdMs;
    if (nowMs < state.startMs + phaseMs) return;
    state.startMs += phaseMs;
    if (state.crossfading) {
      state.currentFrame = state.targetFrame;
      state.targetFrame = randomFrameExcluding(state.currentFrame);
      state.holdMs = Math.floor(Math.random() * 600);
      state.crossfading = false;
    } else {
      state.durationMs = (400 + Math.floor(Math.random() * 400)) / speedMultiplier;
      state.crossfading = true;
    }
  }
}

function drawSlotImage(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number,
  img: HTMLImageElement,
  alpha: number,
): void {
  ctx.globalAlpha = alpha;
  ctx.drawImage(img, x, y, w, h);
}

interface DustContainerImageSet {
  getEmpty: () => HTMLImageElement;
  getFull: () => HTMLImageElement;
  getFrame: (index: number) => HTMLImageElement;
  /** Label used in the dev-mode missing-frame warning. */
  label: string;
}

const NATIVE_IMAGE_SET: DustContainerImageSet = {
  getEmpty: getDustContainerEmptyImg,
  getFull: getDustContainerFullImg,
  getFrame: getDustContainerAnimFrame,
  label: 'native',
};

const HUD_IMAGE_SET: DustContainerImageSet = {
  getEmpty: getDustContainerHudEmptyImg,
  getFull: getDustContainerHudFullImg,
  getFrame: getDustContainerHudAnimFrame,
  label: 'hud',
};

function drawAnimatedDustContainerInternal(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number,
  slotIndex: number,
  nowMs: number,
  images: DustContainerImageSet,
  alpha = 1,
  speedMultiplier = 1,
): void {
  let state = _slotStates.get(slotIndex);
  // Only reset on clock rollback (e.g. slot index reuse across sessions); normal forward
  // progress — including large gaps from a backgrounded tab — is handled by advanceSlotState.
  if (state === undefined || nowMs < state.startMs - 60_000) {
    state = createSlotState(nowMs, speedMultiplier);
    _slotStates.set(slotIndex, state);
  } else {
    advanceSlotState(state, nowMs, speedMultiplier);
  }

  const imgA = images.getFrame(state.currentFrame);
  const imgB = images.getFrame(state.targetFrame);
  const readyA = isSpriteReady(imgA);
  const readyB = isSpriteReady(imgB);

  if (!state.crossfading || !readyB) {
    // Holding on the settled frame, or the next frame isn't ready yet: draw current frame only.
    if (readyA) {
      ctx.save();
      drawSlotImage(ctx, x, y, w, h, imgA, alpha);
      ctx.restore();
    } else {
      drawMissingFrameFallback(ctx, x, y, w, h, state, images);
    }
    return;
  }

  if (readyA) {
    // "Reveal" crossfade: the current frame is always drawn fully opaque underneath, and the
    // target frame fades in on top of it (alpha 0 -> 1). This guarantees some frame is always
    // at 100% opacity throughout the transition — there's never a moment where both frames are
    // partially transparent and the container looks faded/washed out. Once the target frame
    // reaches full opacity, it becomes the new opaque base and a fresh target starts fading in
    // on top of it.
    const t = Math.max(0, Math.min(1, (nowMs - state.startMs) / state.durationMs));
    ctx.save();
    drawSlotImage(ctx, x, y, w, h, imgA, alpha);
    drawSlotImage(ctx, x, y, w, h, imgB, t * alpha);
    ctx.restore();
  } else {
    drawMissingFrameFallback(ctx, x, y, w, h, state, images);
  }
}

function drawEmptyDustContainer(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number,
  images: DustContainerImageSet,
): void {
  const emptyImg = images.getEmpty();
  if (isSpriteReady(emptyImg)) {
    ctx.drawImage(emptyImg, x, y, w, h);
    return;
  }
  ctx.fillStyle = 'rgba(12,10,7,0.88)';
  ctx.fillRect(x, y, w, h);
  ctx.strokeStyle = 'rgba(105,82,35,0.7)';
  ctx.lineWidth = 1;
  ctx.strokeRect(x + 0.5, y + 0.5, w - 1, h - 1);
}

function drawMissingFrameFallback(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number,
  state: SlotAnimState,
  images: DustContainerImageSet,
): void {
  if (import.meta.env?.DEV === true && !state._warnedMissingFrame) {
    state._warnedMissingFrame = true;
    console.warn(`[dustContainerAnimation] ${images.label} animation frame not ready — using fallback rendering`);
  }
  const fallback = images.getFull();
  if (isSpriteReady(fallback)) {
    ctx.drawImage(fallback, x, y, w, h);
  } else {
    // Fallback rectangle while loading image
    ctx.fillStyle = 'rgba(92,65,8,0.96)';
    ctx.fillRect(x, y, w, h);
    ctx.strokeStyle = '#d4a84b';
    ctx.lineWidth = 1;
    ctx.strokeRect(x + 0.5, y + 0.5, w - 1, h - 1);
    ctx.fillStyle = '#ffd85a';
    ctx.fillRect(x + 2, y + 2, Math.max(1, w - 4), Math.max(1, h - 4));
  }
}

/**
 * Renders a dust container slot onto a canvas context, applying a smooth randomized
 * crossfade between animation frames when the slot is filled. Uses the native-resolution
 * art; intended for loadout/inventory menus that render at or near native sprite size.
 */
export function drawAnimatedDustContainer(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  isFilled: boolean,
  slotIndex: number,
  nowMs: number,
): void {
  if (!isFilled) {
    drawEmptyDustContainer(ctx, x, y, w, h, NATIVE_IMAGE_SET);
    return;
  }
  drawAnimatedDustContainerInternal(ctx, x, y, w, h, slotIndex, nowMs, NATIVE_IMAGE_SET);
}

/**
 * Same as {@link drawAnimatedDustContainer}, but draws the pre-downsampled HUD-resolution
 * frames instead of scaling the native art at runtime. Use this for the small in-game HUD
 * slots to avoid runtime-downsample artifacts (e.g. a stray dark outline column surviving
 * nearest-neighbor sampling).
 */
export function drawAnimatedDustContainerHud(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  isFilled: boolean,
  slotIndex: number,
  nowMs: number,
): void {
  let fillState = _slotFillStates.get(slotIndex);
  if (fillState === undefined) {
    // A newly observed slot is already in its settled state; only subsequent
    // live mote-count changes should animate.
    fillState = { isFilled, transitionStartMs: nowMs - HUD_FILL_CROSSFADE_MS };
    _slotFillStates.set(slotIndex, fillState);
  } else if (fillState.isFilled !== isFilled) {
    fillState.isFilled = isFilled;
    fillState.transitionStartMs = nowMs;
  }

  const transitionT = Math.max(0, Math.min(1, (nowMs - fillState.transitionStartMs) / HUD_FILL_CROSSFADE_MS));
  const isTransitioning = transitionT < 1;
  const fullAlpha = isTransitioning ? (fillState.isFilled ? transitionT : 1 - transitionT) : (isFilled ? 1 : 0);

  // The empty sprite stays fully opaque underneath. Damage rapidly fades the
  // full sprite away; regeneration performs the exact reverse, one changed
  // slot at a time as the live mote count increases.
  drawEmptyDustContainer(ctx, x, y, w, h, HUD_IMAGE_SET);
  if (fullAlpha > 0) {
    drawAnimatedDustContainerInternal(
      ctx, x, y, w, h, slotIndex, nowMs, HUD_IMAGE_SET,
      fullAlpha, HUD_AMBIENT_CROSSFADE_SPEED_MULTIPLIER,
    );
  }
}

/**
 * Initiates a real-time requestAnimationFrame loop on a DOM canvas element in menus,
 * running the randomized crossfade animation. Returns a cleanup callback to cancel the loop.
 */
export function startDustContainerCanvasAnimation(
  canvas: HTMLCanvasElement,
  isFilled: boolean,
  slotIndex: number,
): () => void {
  const ctxOrNull = canvas.getContext('2d');
  if (ctxOrNull === null) return () => { /* no-op */ };
  const ctx = ctxOrNull;

  let rafId = 0;
  let running = true;

  function frame(): void {
    if (!running) return;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    drawAnimatedDustContainer(ctx, 0, 0, canvas.width, canvas.height, isFilled, slotIndex, performance.now());
    rafId = requestAnimationFrame(frame);
  }

  rafId = requestAnimationFrame(frame);

  return () => {
    running = false;
    if (rafId !== 0) {
      cancelAnimationFrame(rafId);
      rafId = 0;
    }
  };
}

/** Test-only: clears all per-slot animation state and preload flags. */
export function _resetDustContainerAnimationStateForTests(): void {
  _slotStates.clear();
  _slotFillStates.clear();
  _hudFramesPreloadStarted = false;
}
