/**
 * snapshotAllocating.ts — Allocating (non-pooled) world snapshot factory.
 *
 * Extracted from snapshot.ts to separate the allocation-heavy, non-hot-path
 * `createSnapshot` function from the performance-critical reusable snapshot
 * API in snapshot.ts.
 *
 * The allocating snapshot is useful for testing, debug tools, and one-shot
 * reads.  For the hot render path, use `createReusableSnapshot` +
 * `updateSnapshotInPlace` from `snapshot.ts` instead.
 */

import { WorldState } from '../sim/world';
import { ClusterState } from '../sim/clusters/state';
import { INFLUENCE_RADIUS_WORLD } from '../sim/clusters/binding';
import { DASH_COOLDOWN_TICKS } from '../sim/clusters/dashConstants';
import { MAX_PARTICLES } from '../sim/particles/state';
import type { WorldSnapshot, ClusterSnapshot } from './snapshotTypes';

/**
 * Creates a brand-new `WorldSnapshot` by allocating fresh arrays/objects from
 * the current `WorldState`.  Unlike the reusable snapshot, this allocates on
 * every call and is not suitable for the per-frame render hot path.
 */
export function createSnapshot(world: WorldState): WorldSnapshot {
  const clusterSnapshots: ClusterSnapshot[] = [];
  for (let i = 0; i < world.clusters.length; i++) {
    const c: ClusterState = world.clusters[i];
    clusterSnapshots.push({
      entityId:              c.entityId,
      positionXWorld:        c.positionXWorld,
      positionYWorld:        c.positionYWorld,
      velocityXWorld:        c.velocityXWorld,
      velocityYWorld:        c.velocityYWorld,
      isAliveFlag:           c.isAliveFlag,
      isPlayerFlag:          c.isPlayerFlag,
      healthPoints:          c.healthPoints,
      maxHealthPoints:       c.maxHealthPoints,
      influenceRadiusWorld:  INFLUENCE_RADIUS_WORLD,
      dashCooldownTicks:     c.dashCooldownTicks,
      maxDashCooldownTicks:  DASH_COOLDOWN_TICKS,
      dashRechargeAnimTicks: c.dashRechargeAnimTicks,
      halfWidthWorld:        c.halfWidthWorld,
      halfHeightWorld:       c.halfHeightWorld,
      isFlyingEyeFlag:          c.isFlyingEyeFlag,
      flyingEyeFacingAngleRad:  c.flyingEyeFacingAngleRad,
      flyingEyeElementKind:     c.flyingEyeElementKind,
      isRollingEnemyFlag:       c.isRollingEnemyFlag,
      rollingEnemySpriteIndex:  c.rollingEnemySpriteIndex,
      rollingEnemyRollAngleRad: c.rollingEnemyRollAngleRad,
      isFacingLeftFlag:          c.isFacingLeftFlag,
      isSprintingFlag:           c.isSprintingFlag,
      isCrouchingFlag:           c.isCrouchingFlag,
      isGroundedFlag:            c.isGroundedFlag,
      isWallSlidingFlag:         c.isWallSlidingFlag,
      playerIdleAnimState:       c.playerIdleAnimState,
      isRockElementalFlag:              c.isRockElementalFlag,
      rockElementalState:               c.rockElementalState,
      rockElementalActivationProgress:  c.rockElementalActivationProgress,
      rockElementalOrbitAngleRad:       c.rockElementalOrbitAngleRad,
      rockElementalDustCount:           c.rockElementalDustCount,
      isRadiantTetherFlag:              c.isRadiantTetherFlag,
      radiantTetherState:               c.radiantTetherState,
      radiantTetherStateTicks:          c.radiantTetherStateTicks,
      radiantTetherBaseAngleRad:        c.radiantTetherBaseAngleRad,
      radiantTetherChainCount:          c.radiantTetherChainCount,
      isRadiantWebFlag:                 c.isRadiantWebFlag,
      radiantWebState:                  c.radiantWebState,
      radiantWebStateTicks:             c.radiantWebStateTicks,
      isCrimsonWizardFlag:              c.isCrimsonWizardFlag,
      crimsonWizardState:               c.crimsonWizardState,
      crimsonWizardStateTicks:          c.crimsonWizardStateTicks,
      crimsonWizardFacingX:             c.crimsonWizardFacingX,
      crimsonWizardTelegraphTicks:      c.crimsonWizardTelegraphTicks,
      isGrappleHunterFlag:              c.isGrappleHunterFlag,
      grappleHunterState:               c.grappleHunterState,
      grappleHunterChainStartIndex:     c.grappleHunterChainStartIndex,
      grappleHunterTipXWorld:           c.grappleHunterTipXWorld,
      grappleHunterTipYWorld:           c.grappleHunterTipYWorld,
      isWallSnakeFlag:                  c.isWallSnakeFlag,
      isNeedleSnakeFlag:                c.isNeedleSnakeFlag,
      snakeAiState:                     c.snakeAiState,
      snakeAiStateTicks:                c.snakeAiStateTicks,
      snakeIsOnWallFlag:                c.snakeIsOnWallFlag,
      snakeHeadDirXWorld:               c.snakeHeadDirXWorld,
      snakeHeadDirYWorld:               c.snakeHeadDirYWorld,
      snakeSlitherPhaseRad:             c.snakeSlitherPhaseRad,
      isHighVelocityAttacking:          c.isHighVelocityAttacking,
      invulnerabilityTicks:             c.invulnerabilityTicks,
      hurtTicks:                        c.hurtTicks,
      isSlimeFlag:                c.isSlimeFlag,
      isLargeSlimeFlag:           c.isLargeSlimeFlag,
      largeSlimeDustOrbitAngleRad: c.largeSlimeDustOrbitAngleRad,
      isWheelEnemyFlag:           c.isWheelEnemyFlag,
      wheelRollAngleRad:          c.wheelRollAngleRad,
      isBeetleFlag:                  c.isBeetleFlag,
      beetleAiState:                 c.beetleAiState,
      beetleSurfaceNormalXWorld:     c.beetleSurfaceNormalXWorld,
      beetleSurfaceNormalYWorld:     c.beetleSurfaceNormalYWorld,
      beetleIsFlightModeFlag:        c.beetleIsFlightModeFlag,
      isBubbleEnemyFlag:             c.isBubbleEnemyFlag,
      isIceBubbleFlag:               c.isIceBubbleFlag,
      bubbleState:                   c.bubbleState,
      bubbleOrbitAngleRad:           c.bubbleOrbitAngleRad,
      isSquareStampedeFlag:          c.isSquareStampedeFlag,
      squareStampedeSlotIndex:       c.squareStampedeSlotIndex,
      squareStampedeBaseHalfSizeWorld: c.squareStampedeBaseHalfSizeWorld,
      isGoldenMimicFlag:             c.isGoldenMimicFlag,
      isGoldenMimicYFlippedFlag:     c.isGoldenMimicYFlippedFlag,
      goldenMimicState:              c.goldenMimicState,
      goldenMimicFadeAlpha:          c.goldenMimicFadeAlpha,
      isBeeSwarmFlag:                c.isBeeSwarmFlag,
      beeSwarmSlotIndex:             c.beeSwarmSlotIndex,
      beeSwarmState:                 c.beeSwarmState,
      beeSwarmOrbitAngleRad:         c.beeSwarmOrbitAngleRad,
      isWebSpiderFlag:               c.isWebSpiderFlag,
      webSpiderState:                c.webSpiderState,
      webSpiderAnchorXWorld:         c.webSpiderAnchorXWorld,
      webSpiderAnchorYWorld:         c.webSpiderAnchorYWorld,
      isDustConstellationFlag:       c.isDustConstellationFlag,
      isDustConstellationLargeFlag:  c.isDustConstellationLargeFlag,
      dustConstellationState:        c.dustConstellationState,
      dustConstellationStateTicks:   c.dustConstellationStateTicks,
      dustConstellationSlotIndex:    c.dustConstellationSlotIndex,
      dustConstellationPatternIndex: c.dustConstellationPatternIndex,
      dustConstellationActiveBeamIndex: c.dustConstellationActiveBeamIndex,
      isOrbitalDustCoreFlag:          c.isOrbitalDustCoreFlag,
      isOrbitalDustCoreLargeFlag:     c.isOrbitalDustCoreLargeFlag,
      orbitalDustCoreState:           c.orbitalDustCoreState,
      orbitalDustCoreStateTicks:      c.orbitalDustCoreStateTicks,
      orbitalDustCoreSlotIndex:       c.orbitalDustCoreSlotIndex,
      orbitalDustCoreExposedRing:     c.orbitalDustCoreExposedRing,
      orbitalDustCoreRing0Health:     c.orbitalDustCoreRing0Health,
      orbitalDustCoreRing1Health:     c.orbitalDustCoreRing1Health,
      orbitalDustCoreRing2Health:     c.orbitalDustCoreRing2Health,
      orbitalDustCoreRing3Health:     c.orbitalDustCoreRing3Health,
      orbitalDustCorePulseRadius:     c.orbitalDustCorePulseRadius,
      orbitalDustCorePulseActiveFlag: c.orbitalDustCorePulseActiveFlag,
      orbitalDustCoreShieldFlashTicks: c.orbitalDustCoreShieldFlashTicks,
      orbitalDustCoreCorePulseTicks:  c.orbitalDustCoreCorePulseTicks,
      isDustBlockMimicFlag:            c.isDustBlockMimicFlag,
      isDustBlockMimicLargeFlag:       c.isDustBlockMimicLargeFlag,
      dustBlockMimicState:             c.dustBlockMimicState,
      dustBlockMimicStateTicks:        c.dustBlockMimicStateTicks,
      dustBlockMimicSlotIndex:         c.dustBlockMimicSlotIndex,
      dustBlockMimicSpawnXWorld:       c.dustBlockMimicSpawnXWorld,
      dustBlockMimicSpawnYWorld:       c.dustBlockMimicSpawnYWorld,
      dustBlockMimicBobPhaseRad:       c.dustBlockMimicBobPhaseRad,
      dustBlockMimicAttackCooldownTicks: c.dustBlockMimicAttackCooldownTicks,
      dustBlockMimicLungeDirXWorld:    c.dustBlockMimicLungeDirXWorld,
      dustBlockMimicLungeDirYWorld:    c.dustBlockMimicLungeDirYWorld,
      dustBlockMimicLungeDistCovered:  c.dustBlockMimicLungeDistCovered,
      dustBlockMimicLungeHitPlayerFlag: c.dustBlockMimicLungeHitPlayerFlag,
      dustBlockMimicHitFlashTicks:     c.dustBlockMimicHitFlashTicks,
      isDustWeaverArchitectFlag:              c.isDustWeaverArchitectFlag,
      isDustWeaverArchitectLargeFlag:         c.isDustWeaverArchitectLargeFlag,
      dustWeaverArchitectState:               c.dustWeaverArchitectState,
      dustWeaverArchitectStateTicks:          c.dustWeaverArchitectStateTicks,
      dustWeaverArchitectSlotIndex:           c.dustWeaverArchitectSlotIndex,
      dustWeaverArchitectSpawnXWorld:         c.dustWeaverArchitectSpawnXWorld,
      dustWeaverArchitectSpawnYWorld:         c.dustWeaverArchitectSpawnYWorld,
      dustWeaverArchitectBobPhaseRad:         c.dustWeaverArchitectBobPhaseRad,
      dustWeaverArchitectAttackCooldownTicks: c.dustWeaverArchitectAttackCooldownTicks,
      dustWeaverArchitectBuildSiteXWorld:     c.dustWeaverArchitectBuildSiteXWorld,
      dustWeaverArchitectBuildSiteYWorld:     c.dustWeaverArchitectBuildSiteYWorld,
      dustWeaverArchitectBuildPatternIndex:   c.dustWeaverArchitectBuildPatternIndex,
      dustWeaverArchitectHitFlashTicks:       c.dustWeaverArchitectHitFlashTicks,
      dustWeaverArchitectRangePressureTicks:  c.dustWeaverArchitectRangePressureTicks,
      dustWeaverArchitectNailCooldownTicks:   c.dustWeaverArchitectNailCooldownTicks,
      isVoidSingularityFlag:             c.isVoidSingularityFlag,
      isVoidSingularityPairFlag:         c.isVoidSingularityPairFlag,
      voidSingularityState:              c.voidSingularityState,
      voidSingularityStateTicks:         c.voidSingularityStateTicks,
      voidSingularitySlotIndex:          c.voidSingularitySlotIndex,
      voidSingularitySpawnXWorld:        c.voidSingularitySpawnXWorld,
      voidSingularitySpawnYWorld:        c.voidSingularitySpawnYWorld,
      voidSingularityBobPhaseRad:        c.voidSingularityBobPhaseRad,
      voidSingularityAbsorbedEnergy:     c.voidSingularityAbsorbedEnergy,
      voidSingularityPulseRadius:        c.voidSingularityPulseRadius,
      voidSingularityPulseActiveFlag:    c.voidSingularityPulseActiveFlag,
      voidSingularityPulseHitPlayerFlag: c.voidSingularityPulseHitPlayerFlag,
      voidSingularityHitFlashTicks:      c.voidSingularityHitFlashTicks,
      voidSingularityPairAngleRad:       c.voidSingularityPairAngleRad,
      voidSingularityWholeCharge:        c.voidSingularityWholeCharge,
      voidSingularityWholeState:         c.voidSingularityWholeState,
      voidSingularityWholeStateTicks:    c.voidSingularityWholeStateTicks,
      isGridBlockEnemyFlag:              c.isGridBlockEnemyFlag,
      gridBlockSizeIndex:                c.gridBlockSizeIndex,
      gridBlockSpeedIndex:               c.gridBlockSpeedIndex,
      gridBlockGlintPhase:               c.gridBlockGlintPhase,
      gridBlockHitFlashTicks:            c.gridBlockHitFlashTicks,
      isGridSnakeEnemyFlag:              c.isGridSnakeEnemyFlag,
      gridSnakeLength:                   c.gridSnakeLength,
      gridSnakeSegmentGridX:             c.gridSnakeSegmentGridX,
      gridSnakeSegmentGridY:             c.gridSnakeSegmentGridY,
      gridSnakePhase:                    c.gridSnakePhase,
      isDustLeechFlag:                   c.isDustLeechFlag,
      dustLeechState:                    c.dustLeechState,
      dustLeechStateTicks:               c.dustLeechStateTicks,
      dustLeechSlotIndex:                c.dustLeechSlotIndex,
      dustLeechSpawnXWorld:              c.dustLeechSpawnXWorld,
      dustLeechSpawnYWorld:              c.dustLeechSpawnYWorld,
      dustLeechBobPhaseRad:              c.dustLeechBobPhaseRad,
      dustLeechSiphonCharge:             c.dustLeechSiphonCharge,
      dustLeechAttackCooldownTicks:      c.dustLeechAttackCooldownTicks,
      dustLeechHitFlashTicks:            c.dustLeechHitFlashTicks,
      isDustEchoFlag:                    c.isDustEchoFlag,
      dustEchoState:                     c.dustEchoState,
      dustEchoStateTicks:                c.dustEchoStateTicks,
      dustEchoLifetimeTicks:             c.dustEchoLifetimeTicks,
      dustEchoOwnerEntityId:             c.dustEchoOwnerEntityId,
      dustEchoSlotIndex:                 c.dustEchoSlotIndex,
      dustEchoLungeDirXWorld:            c.dustEchoLungeDirXWorld,
      dustEchoLungeDirYWorld:            c.dustEchoLungeDirYWorld,
      dustEchoLungeDistCovered:          c.dustEchoLungeDistCovered,
      dustEchoLungeHitPlayerFlag:        c.dustEchoLungeHitPlayerFlag,
      dustEchoLungeCooldownTicks:        c.dustEchoLungeCooldownTicks,
      dustEchoHitFlashTicks:             c.dustEchoHitFlashTicks,
      renderPositionXWorld:          c.positionXWorld,
      renderPositionYWorld:          c.positionYWorld,
    });
  }

  return {
    tick: world.tick,
    particles: {
      positionXWorld:    world.positionXWorld,
      positionYWorld:    world.positionYWorld,
      velocityXWorld:    world.velocityXWorld,
      velocityYWorld:    world.velocityYWorld,
      isAliveFlag:       world.isAliveFlag,
      kindBuffer:        world.kindBuffer,
      ownerEntityId:     world.ownerEntityId,
      ageTicks:          world.ageTicks,
      lifetimeTicks:     world.lifetimeTicks,
      disturbanceFactor: world.disturbanceFactor,
      behaviorMode:      world.behaviorMode,
      particleMoteSlotState: (() => {
        const arr = new Uint8Array(MAX_PARTICLES);
        for (let s = 0; s < world.moteSlotCount; s++) {
          const pidx = world.moteSlotParticleIndex[s];
          if (pidx >= 0 && world.moteSlotState[s] !== 0) arr[pidx] = 1;
        }
        return arr;
      })(),
      noiseTickSeed:     world.noiseTickSeed,
      particleCount:     world.particleCount,
    },
    clusters: clusterSnapshots,
    walls: {
      count:  world.wallCount,
      xWorld: world.wallXWorld,
      yWorld: world.wallYWorld,
      wWorld: world.wallWWorld,
      hWorld: world.wallHWorld,
      isPlatformFlag: world.wallIsPlatformFlag,
      platformEdge: world.wallPlatformEdge,
      themeIndex: world.wallThemeIndex,
      isInvisibleFlag: world.wallIsInvisibleFlag,
      rampOrientationIndex: world.wallRampOrientationIndex,
      isPillarHalfWidthFlag: world.wallIsPillarHalfWidthFlag,
    },
    isGrappleActiveFlag: world.isGrappleActiveFlag,
    isGrappleMissActiveFlag: world.isGrappleMissActiveFlag,
    grappleParticleStartIndex: world.grappleParticleStartIndex,
    isGrappleZipActiveFlag: world.isGrappleZipActiveFlag,
    isGrappleStuckFlag: world.isGrappleStuckFlag,
    grappleAnchorXWorld: world.grappleAnchorXWorld,
    grappleAnchorYWorld: world.grappleAnchorYWorld,
    grappleAnchorNormalXWorld: world.grappleAnchorNormalXWorld,
    grappleAnchorNormalYWorld: world.grappleAnchorNormalYWorld,
    grappleDebugSweepFromXWorld: world.grappleDebugSweepFromXWorld,
    grappleDebugSweepFromYWorld: world.grappleDebugSweepFromYWorld,
    grappleDebugSweepToXWorld:   world.grappleDebugSweepToXWorld,
    grappleDebugSweepToYWorld:   world.grappleDebugSweepToYWorld,
    grappleDebugRawHitXWorld:    world.grappleDebugRawHitXWorld,
    grappleDebugRawHitYWorld:    world.grappleDebugRawHitYWorld,
    isGrappleDebugActiveFlag:    world.isGrappleDebugActiveFlag,
    grappleAttachFxTicks: world.grappleAttachFxTicks,
    grappleAttachFxXWorld: world.grappleAttachFxXWorld,
    grappleAttachFxYWorld: world.grappleAttachFxYWorld,
    grappleProximityBounceTicksLeft:        world.grappleProximityBounceTicksLeft,
    grappleProximityBounceRotationAngleRad: world.grappleProximityBounceRotationAngleRad,
    grappleFailBeamTicksLeft:       world.grappleFailBeamTicksLeft,
    grappleFailBeamTotalTicks:      world.grappleFailBeamTotalTicks,
    grappleFailBeamStartXWorld:     world.grappleFailBeamStartXWorld,
    grappleFailBeamStartYWorld:     world.grappleFailBeamStartYWorld,
    grappleFailBeamEndXWorld:       world.grappleFailBeamEndXWorld,
    grappleFailBeamEndYWorld:       world.grappleFailBeamEndYWorld,
    grappleIceBounceTicksLeft:      world.grappleIceBounceTicksLeft,
    grappleIceBounceTicksTotal:     world.grappleIceBounceTicksTotal,
    grappleIceBounceStartXWorld:    world.grappleIceBounceStartXWorld,
    grappleIceBounceStartYWorld:    world.grappleIceBounceStartYWorld,
    grappleIceBounceEndXWorld:      world.grappleIceBounceEndXWorld,
    grappleIceBounceEndYWorld:      world.grappleIceBounceEndYWorld,
    grappleEmptyFxTicksLeft:        world.grappleEmptyFxTicksLeft,
    grappleEmptyFxTotalTicks:       world.grappleEmptyFxTotalTicks,
    grappleEmptyFxXWorld:           world.grappleEmptyFxXWorld,
    grappleEmptyFxYWorld:           world.grappleEmptyFxYWorld,
    zipImpactFxTicksLeft:           world.zipImpactFxTicksLeft,
    zipImpactFxTotalTicks:          world.zipImpactFxTotalTicks,
    zipImpactFxXWorld:              world.zipImpactFxXWorld,
    zipImpactFxYWorld:              world.zipImpactFxYWorld,
    zipImpactFxScale:               world.zipImpactFxScale,
    zipImpactFxNormalXWorld:        world.zipImpactFxNormalXWorld,
    zipImpactFxNormalYWorld:        world.zipImpactFxNormalYWorld,
    isZipJumpWindowOpenFlag:        world.isZipJumpWindowOpenFlag,
    isPlayerBlockingFlag: world.isPlayerBlockingFlag,
    hasGrappleChargeFlag: world.hasGrappleChargeFlag,
    grappleRechargeRingTicksLeft:  world.grappleRechargeRingTicksLeft,
    grappleRechargeRingTotalTicks: world.grappleRechargeRingTotalTicks,
    isPlayerWeaveActiveFlag: (world.isPlayerPrimaryWeaveActiveFlag === 1 || world.isPlayerSecondaryWeaveActiveFlag === 1) ? 1 : 0,
    characterId: world.characterId,
    grasshopperCount:       world.grasshopperCount,
    grasshopperXWorld:      world.grasshopperXWorld,
    grasshopperYWorld:      world.grasshopperYWorld,
    isGrasshopperAliveFlag: world.isGrasshopperAliveFlag,
    squareStampedeTrailXWorld: world.squareStampedeTrailXWorld,
    squareStampedeTrailYWorld: world.squareStampedeTrailYWorld,
    squareStampedeTrailHead:   world.squareStampedeTrailHead,
    squareStampedeTrailCount:  world.squareStampedeTrailCount,
    squareStampedeTrailStride: world.squareStampedeTrailStride,
    beeSwarmBeeXWorld:         world.beeSwarmBeeXWorld,
    beeSwarmBeeYWorld:         world.beeSwarmBeeYWorld,
    beeSwarmBeeVelXWorld:      world.beeSwarmBeeVelXWorld,
    beeSwarmBeeVelYWorld:      world.beeSwarmBeeVelYWorld,
    isArrowWeaveLoadingFlag:    world.isArrowWeaveLoadingFlag,
    arrowWeaveCurrentMoteCount: world.arrowWeaveCurrentMoteCount,
    playerWeaveAimDirXWorld:    world.playerWeaveAimDirXWorld,
    playerWeaveAimDirYWorld:    world.playerWeaveAimDirYWorld,
    arrowCount:                 world.arrowCount,
    arrowXWorld:                world.arrowXWorld,
    arrowYWorld:                world.arrowYWorld,
    arrowDirXWorld:             world.arrowDirXWorld,
    arrowDirYWorld:             world.arrowDirYWorld,
    arrowMoteCount:             world.arrowMoteCount,
    isArrowStuckFlag:           world.isArrowStuckFlag,
    isArrowHitEnemyFlag:        world.isArrowHitEnemyFlag,
    arrowLifetimeTicksLeft:     world.arrowLifetimeTicksLeft,
    // Shield Sword Weave
    playerSecondaryWeaveId:        world.playerSecondaryWeaveId,
    swordWeaveStateEnum:           world.swordWeaveStateEnum,
    swordWeaveStateTicksElapsed:   world.swordWeaveStateTicksElapsed,
    swordWeaveAngleRad:            world.swordWeaveAngleRad,
    swordWeaveSlashStartAngleRad:  world.swordWeaveSlashStartAngleRad,
    swordWeaveSlashEndAngleRad:    world.swordWeaveSlashEndAngleRad,
    swordWeaveHandAnchorXWorld:    world.swordWeaveHandAnchorXWorld,
    swordWeaveHandAnchorYWorld:    world.swordWeaveHandAnchorYWorld,
    swordWeaveLengthRatio:         world.swordWeaveLengthRatio,
    // Ordered Mote Queue display
    moteGrappleDisplayRadiusWorld: world.moteGrappleDisplayRadiusWorld,
    isMoteSourceOrbitFlag:         world.isMoteSourceOrbitFlag,
    grappleTensionFactor:          world.grappleTensionFactor,
    // Phase 2: geometric grapple wrapping
    isGrappleWrappingEnabled:      world.isGrappleWrappingEnabled,
    grappleWrapPointCount:         world.grappleWrapPointCount,
    grappleWrapPointXWorld:        world.grappleWrapPointXWorld,
    grappleWrapPointYWorld:        world.grappleWrapPointYWorld,
    ropeCount:           world.ropeCount,
    ropeSegmentCount:    world.ropeSegmentCount,
    ropeHalfThickWorld:  world.ropeHalfThickWorld,
    ropeSegPosXWorld:    world.ropeSegPosXWorld,
    ropeSegPosYWorld:    world.ropeSegPosYWorld,
    // Web Spider fading web ring buffer
    webSpiderFadingWebMaxCount:        world.webSpiderFadingWebMaxCount,
    webSpiderFadingWebActiveCount:     world.webSpiderFadingWebActiveCount,
    webSpiderFadingWebFromXWorld:      world.webSpiderFadingWebFromXWorld,
    webSpiderFadingWebFromYWorld:      world.webSpiderFadingWebFromYWorld,
    webSpiderFadingWebToXWorld:        world.webSpiderFadingWebToXWorld,
    webSpiderFadingWebToYWorld:        world.webSpiderFadingWebToYWorld,
    webSpiderFadingWebRemainingTicks:  world.webSpiderFadingWebRemainingTicks,
    webSpiderFadingWebMaxTicks:        world.webSpiderFadingWebMaxTicks,
    constellationMoteXWorld:           world.constellationMoteXWorld,
    constellationMoteYWorld:           world.constellationMoteYWorld,
    constellationMoteVelXWorld:        world.constellationMoteVelXWorld,
    constellationMoteVelYWorld:        world.constellationMoteVelYWorld,
    constellationMoteTargetLocalX:     world.constellationMoteTargetLocalX,
    constellationMoteTargetLocalY:     world.constellationMoteTargetLocalY,
    constellationMotePulsePhaseRad:    world.constellationMotePulsePhaseRad,
    odcMoteAngleRad:                   world.odcMoteAngleRad,
    odcMoteRadiusWorld:                world.odcMoteRadiusWorld,
    odcMoteAliveFlag:                  world.odcMoteAliveFlag,
    odcMotePulsePhaseRad:              world.odcMotePulsePhaseRad,
    dbmMoteXWorld:                     world.dbmMoteXWorld,
    dbmMoteYWorld:                     world.dbmMoteYWorld,
    dbmMoteVelXWorld:                  world.dbmMoteVelXWorld,
    dbmMoteVelYWorld:                  world.dbmMoteVelYWorld,
    dbmMoteTargetLocalX:               world.dbmMoteTargetLocalX,
    dbmMoteTargetLocalY:               world.dbmMoteTargetLocalY,
    dbmMotePulsePhaseRad:              world.dbmMotePulsePhaseRad,
    dwaMoteAngleRad:             world.dwaMoteAngleRad,
    dwaMotePulsePhaseRad:        world.dwaMotePulsePhaseRad,
    vsMoteAngleRad:              world.vsMoteAngleRad,
    vsMoteRadiusWorld:           world.vsMoteRadiusWorld,
    vsMotePulsePhaseRad:         world.vsMotePulsePhaseRad,
    dlMoteAngleRad:              world.dlMoteAngleRad,
    dlMotePulsePhaseRad:         world.dlMotePulsePhaseRad,
    deMoteOffsetXWorld:          world.deMoteOffsetXWorld,
    deMoteOffsetYWorld:          world.deMoteOffsetYWorld,
    deMotePulsePhaseRad:         world.deMotePulsePhaseRad,
    vspProjXWorld:               world.vspProjXWorld,
    vspProjYWorld:               world.vspProjYWorld,
    vspProjVelXWorld:            world.vspProjVelXWorld,
    vspProjVelYWorld:            world.vspProjVelYWorld,
    vspProjLifetimeTicks:        world.vspProjLifetimeTicks,
    vspProjAliveFlag:            world.vspProjAliveFlag,
    cwFireDustXWorld:            world.cwFireDustXWorld,
    cwFireDustYWorld:            world.cwFireDustYWorld,
    cwFireDustAgeTicks:          world.cwFireDustAgeTicks,
    cwFireDustLifetimeTicks:     world.cwFireDustLifetimeTicks,
    cwFireDustColorIndex:        world.cwFireDustColorIndex,
    cwFireDustAliveFlag:         world.cwFireDustAliveFlag,
    cwSmokeXWorld:               world.cwSmokeXWorld,
    cwSmokeYWorld:               world.cwSmokeYWorld,
    cwSmokeAgeTicks:             world.cwSmokeAgeTicks,
    cwSmokeLifetimeTicks:        world.cwSmokeLifetimeTicks,
    cwSmokeAliveFlag:            world.cwSmokeAliveFlag,
    cwProjectileXWorld:          world.cwProjectileXWorld,
    cwProjectileYWorld:          world.cwProjectileYWorld,
    cwProjectileType:            world.cwProjectileType,
    cwProjectileAliveFlag:       world.cwProjectileAliveFlag,
    architectBlockCount:         world.architectBlockCount,
    architectBlockXWorld:        world.architectBlockXWorld,
    architectBlockYWorld:        world.architectBlockYWorld,
    architectBlockHealth:        world.architectBlockHealth,
    architectBlockMaxHealth:     world.architectBlockMaxHealth,
    architectBlockLifetimeTicks: world.architectBlockLifetimeTicks,
    architectBlockGraceTicks:    world.architectBlockGraceTicks,
    architectBlockFormTicks:     world.architectBlockFormTicks,
    architectBlockCrumbleTicks:  world.architectBlockCrumbleTicks,
    architectBlockState:         world.architectBlockState,
    isArchitectBlockAliveFlag:   world.isArchitectBlockAliveFlag,
    architectBlockOwnerSlot:     world.architectBlockOwnerSlot,
    // Dust Nail projectiles — shared typed-array views.
    dwaNailXWorld:               world.dwaNailXWorld,
    dwaNailYWorld:               world.dwaNailYWorld,
    dwaNailVelXWorld:            world.dwaNailVelXWorld,
    dwaNailVelYWorld:            world.dwaNailVelYWorld,
    dwaNailLifetimeTicks:        world.dwaNailLifetimeTicks,
    isDwaNailAliveFlag:          world.isDwaNailAliveFlag,
  };
}
