import type { WorldState } from '../world';
import { applyPlayerDamageWithKnockback } from '../playerDamage';
import * as C from './needleUrchinConfig';

export function segmentAabbHitT(x0:number,y0:number,x1:number,y1:number,minX:number,minY:number,maxX:number,maxY:number):number|null{const dx=x1-x0,dy=y1-y0;let lo=0,hi=1;for(const [p,d,a,b] of [[x0,dx,minX,maxX],[y0,dy,minY,maxY]]){if(Math.abs(d)<1e-9){if(p<a||p>b)return null;}else{let t0=(a-p)/d,t1=(b-p)/d;if(t0>t1)[t0,t1]=[t1,t0];lo=Math.max(lo,t0);hi=Math.min(hi,t1);if(lo>hi)return null;}}return lo;}
export function shouldTriggerNeedleUrchin(dx:number,dy:number,vx:number,vy:number):boolean{return dx*dx+dy*dy<=C.NEEDLE_URCHIN_TRIGGER_RADIUS_WORLD**2&&Math.hypot(vx,vy)>C.NEEDLE_URCHIN_TRIGGER_SPEED_WORLD_PER_SEC;}
export function fireNeedleBurst(world:WorldState,u:import('./state').ClusterState):void{const p=world.clusters[0],slot=u.needleUrchinSlotIndex;if(!p||slot<0)return;const base=Math.atan2(p.positionYWorld-u.positionYWorld,p.positionXWorld-u.positionXWorld);u.needleUrchinBurstPhaseRad=base;for(let i=0;i<C.NEEDLE_URCHIN_NEEDLES_PER_BURST;i++){const f=slot*C.NEEDLE_URCHIN_NEEDLES_PER_BURST+i,a=base+i*Math.PI*2/C.NEEDLE_URCHIN_NEEDLES_PER_BURST,dx=Math.cos(a),dy=Math.sin(a);world.needleProjectileXWorld[f]=u.positionXWorld+dx*C.NEEDLE_PROJECTILE_SPAWN_RADIUS_WORLD;world.needleProjectileYWorld[f]=u.positionYWorld+dy*C.NEEDLE_PROJECTILE_SPAWN_RADIUS_WORLD;world.needleProjectilePrevXWorld[f]=world.needleProjectileXWorld[f];world.needleProjectilePrevYWorld[f]=world.needleProjectileYWorld[f];world.needleProjectileVelXWorld[f]=dx*C.NEEDLE_PROJECTILE_SPEED_WORLD_PER_SEC;world.needleProjectileVelYWorld[f]=dy*C.NEEDLE_PROJECTILE_SPEED_WORLD_PER_SEC;world.needleProjectileLifetimeTicks[f]=C.NEEDLE_PROJECTILE_LIFETIME_TICKS;world.needleProjectileAliveFlag[f]=1;world.needleProjectileOwnerSlot[f]=slot;}}
export function applyNeedleUrchinAI(world:WorldState):void{const p=world.clusters[0];if(!p)return;for(const u of world.clusters){if(u.isNeedleUrchinFlag!==1||u.isAliveFlag===0)continue;u.velocityXWorld=0;u.velocityYWorld=0;if(u.needleUrchinShotFlashTicks>0)u.needleUrchinShotFlashTicks--;const ok=shouldTriggerNeedleUrchin(p.positionXWorld-u.positionXWorld,p.positionYWorld-u.positionYWorld,p.velocityXWorld,p.velocityYWorld);if(u.needleUrchinState===C.NEEDLE_URCHIN_STATE_IDLE){if(ok){u.needleUrchinState=C.NEEDLE_URCHIN_STATE_TELEGRAPH;u.needleUrchinStateTicks=0;}}else if(u.needleUrchinState===C.NEEDLE_URCHIN_STATE_TELEGRAPH){if(!ok){u.needleUrchinState=0;u.needleUrchinStateTicks=0;}else if(++u.needleUrchinStateTicks>=C.NEEDLE_URCHIN_TELEGRAPH_TICKS){fireNeedleBurst(world,u);u.needleUrchinState=C.NEEDLE_URCHIN_STATE_COOLDOWN;u.needleUrchinStateTicks=C.NEEDLE_URCHIN_COOLDOWN_TICKS;u.needleUrchinShotFlashTicks=C.NEEDLE_URCHIN_SHOT_FLASH_TICKS;}}else if(--u.needleUrchinStateTicks<=0){u.needleUrchinState=0;u.needleUrchinStateTicks=0;}}}
export function tickNeedleUrchinProjectiles(world:WorldState):void{const p=world.clusters[0],dt=world.dtMs*.001;for(let i=0;i<world.needleProjectileAliveFlag.length;i++){if(!world.needleProjectileAliveFlag[i])continue;const x0=world.needleProjectileXWorld[i],y0=world.needleProjectileYWorld[i],x1=x0+world.needleProjectileVelXWorld[i]*dt,y1=y0+world.needleProjectileVelYWorld[i]*dt;world.needleProjectilePrevXWorld[i]=x0;world.needleProjectilePrevYWorld[i]=y0;let best=2,hitPlayer=false;if(p&&p.isAliveFlag===1){const t=segmentAabbHitT(x0,y0,x1,y1,p.positionXWorld-p.halfWidthWorld-C.NEEDLE_PROJECTILE_HALF_WIDTH_WORLD,p.positionYWorld-p.halfHeightWorld-C.NEEDLE_PROJECTILE_HALF_WIDTH_WORLD,p.positionXWorld+p.halfWidthWorld+C.NEEDLE_PROJECTILE_HALF_WIDTH_WORLD,p.positionYWorld+p.halfHeightWorld+C.NEEDLE_PROJECTILE_HALF_WIDTH_WORLD);if(t!==null){best=t;hitPlayer=true;}}for(let w=0;w<world.wallCount;w++){const t=segmentAabbHitT(x0,y0,x1,y1,world.wallXWorld[w],world.wallYWorld[w],world.wallXWorld[w]+world.wallWWorld[w],world.wallYWorld[w]+world.wallHWorld[w]);if(t!==null&&t<best){best=t;hitPlayer=false;}}if(best<=1){world.needleProjectileXWorld[i]=x0+(x1-x0)*best;world.needleProjectileYWorld[i]=y0+(y1-y0)*best;world.needleProjectileAliveFlag[i]=0;if(hitPlayer&&p)applyPlayerDamageWithKnockback(p,C.NEEDLE_PROJECTILE_DAMAGE,world.needleProjectileXWorld[i],world.needleProjectileYWorld[i],{bypassMomentumInvulnerability:true});continue;}world.needleProjectileXWorld[i]=x1;world.needleProjectileYWorld[i]=y1;if(world.needleProjectileLifetimeTicks[i]>0)world.needleProjectileLifetimeTicks[i]--;if(world.needleProjectileLifetimeTicks[i]===0||x1<0||y1<0||x1>world.worldWidthWorld||y1>world.worldHeightWorld)world.needleProjectileAliveFlag[i]=0;}}
