export const MAX_NEEDLE_URCHINS = 8;
export const NEEDLE_URCHIN_NEEDLES_PER_BURST = 12;
export const NEEDLE_URCHIN_HP = 3;
export const NEEDLE_URCHIN_HALF_SIZE_WORLD = 6;

export const NEEDLE_URCHIN_TRIGGER_RADIUS_WORLD = 96;
export const NEEDLE_URCHIN_TRIGGER_SPEED_WORLD_PER_SEC = 80;
export const NEEDLE_URCHIN_TELEGRAPH_TICKS = 15;
export const NEEDLE_URCHIN_COOLDOWN_TICKS = 90;
export const NEEDLE_URCHIN_SHOT_FLASH_TICKS = 8;
export const NEEDLE_URCHIN_HIT_FLASH_TICKS = 6;

export const NEEDLE_PROJECTILE_SPEED_WORLD_PER_SEC = 180;
export const NEEDLE_PROJECTILE_LIFETIME_TICKS = 90;
export const NEEDLE_PROJECTILE_LENGTH_WORLD = 8;
export const NEEDLE_PROJECTILE_HALF_WIDTH_WORLD = 0.75;
export const NEEDLE_PROJECTILE_DAMAGE = 1;
export const NEEDLE_PROJECTILE_SPAWN_RADIUS_WORLD = 7;
export const NEEDLE_COLLISION_T_EPSILON = 1e-6;

export const NEEDLE_URCHIN_STATE_IDLE = 0;
export const NEEDLE_URCHIN_STATE_TELEGRAPH = 1;
export const NEEDLE_URCHIN_STATE_COOLDOWN = 2;
