export const MAX_SHADOW_ENEMIES = 4;
export const SHADOW_PATH_CAPACITY = 1800;
export const SHADOW_HP = 1;

export const SHADOW_HALF_WIDTH_WORLD = 3.5;
export const SHADOW_HALF_HEIGHT_WORLD = 10;
export const SHADOW_FOLLOW_SPEED_WORLD_PER_SEC = 150;

export const SHADOW_START_DELAY_TICKS = 90;
export const SHADOW_REPHASE_DELAY_TICKS = 30;
export const SHADOW_TELEPORT_RESET_DISTANCE_WORLD = 96;
export const SHADOW_FATAL_OVERLAP_EPSILON_WORLD = 0.25;
